### ISSUE TITLE
vue-output-target: Can't handle updating v-model value when the event name provided is on camelCase

### ISSUE THREAD

**Issue by jonnelbergonia-vennbio** [ionic-team/stencil-ds-output-targets#262]
I declared a custom event named `ivInput` on my custom component

![image](https://user-images.githubusercontent.com/104967919/174043067-3dc59cb5-5473-4d96-b226-aaf57b8bf4e4.png)

And set the vue component model config on my `stencil.config.js`

![image](https://user-images.githubusercontent.com/104967919/174043410-f7d48df5-47ce-45f2-b450-3e83767763a3.png)

But when I tried to use `v-model` on my Vue app, the model value is not updating. I checked the `utils.ts` and found out that the `eventName` is being converted to lower case (line 79).

`eventName` string case should not be converted to lower case under the hood and should be matched exactly with what is being provided on the config. IMO

![image](https://user-images.githubusercontent.com/104967919/174042442-120a6b39-c772-4c20-b27d-59ea98f0bc20.png)

**Comment by christiancooksponge** [comment]
Had the same problem too, worked around it in the same fashion by declaring a kebab-case `eventName`. Not ideal but it works for the time being!

**Comment by rallu** [comment]
Same problem and same fix seems to be working.

**Comment by mayerraphael** [comment]
This is fixed now with Vue 3.2.38 onwards: https://github.com/vuejs/core/issues/5401#issuecomment-1282366003

@rwaskiewicz  Please fix the VueJS output target. With 3.2.38, which was released 8 months ago, VueJS works with any custom event names.

The problem now is that the events are still converted to lowercase in the output target:
https://github.com/ionic-team/stencil-ds-output-targets/blob/cc2452b8d3e369f1ebbf165572b6e215e50c5244/packages/vue-output-target/vue-component-lib/utils.ts#L84

This should be at least configurable to be backwards compatible.

**Comment by seanwuapps** [comment]
seems like it's been a while and the issues still persists. 
ionic seems to bypass this by using a kebabCase converter function:  

https://github.com/ionic-team/ionic-framework/blob/main/packages/vue/src/ionic-vue.ts#L19
and replacing the addEventListener helper functions in ionic's `initialize` call...

I think removing the `.toLowerCase()` part in the `adddEventListener` call is the right way to go about this.
