### ISSUE TITLE
bug: Message `Failed to serialize light DOM` logged when resolving components

### ISSUE THREAD

**Issue by dwirz** [ionic-team/stencil-ds-output-targets#561]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/.github/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil-ds-output-targets/issues) that already report this problem, without success.

### Stencil Version

4.22.3

### Stencil Framework Output Target

React

### Stencil Framework Output Target Version

0.7.4

### Current Behavior

The SSR component resolver does not properly handle all components and produces the following error in the logs:
```
[react-output-target] Failed to serialize light DOM for <my-button href="#" suppressHydrationWarning="true" />: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object. - this may impact the hydration of the component
```

### Expected Behavior

All components and their child components should be resolved correctly during SSR, ensuring that no error messages are logged. The serialization process should handle all component types properly to support seamless hydration.

### Steps to Reproduce

Check out the `stencil-ds-output-targets` run:
```
pnpm install
pnpm build.react
pnpm start.next
```
Open the app on `http://localhost:3000` and look into your terminal.

### Code Reproduction URL

https://github.com/ionic-team/stencil-ds-output-targets

### Additional Information

I submitted two PRs that address the problem:
	1.	Quick Fix: Provides a temporary solution but does not guarantee prevention of future issues. (#563)
	2.	Extended Logic: Adds more comprehensive logic to handle all possible `ReactNode` types. However, since I am not entirely familiar with React’s internals, I cannot guarantee its correctness. (#562)

Feel free to review the PRs, suggest improvements, or close either of them as you see fit.

**Comment by dwirz** [comment]
fixed by #573

**Comment by dgonzalezr** [comment]
I'm still getting the `Failed to serialize light DOM` after updating to the latest `@stencil/core` and @stencil/react-output-target` version 😕 

![Image](https://github.com/user-attachments/assets/387fcac3-8656-4c89-a51b-bf43498cf9a3)

I've provided more details in [this thread in DIscord](https://discord.com/channels/520266681499779082/1329092813102514187).
